src/Entity/Jour.php
<?php

namespace AcMarche\Edr\Entity;

use AcMarche\Edr\Entity\Plaine\Plaine;
use AcMarche\Edr\Entity\Plaine\PlaineTrait;
use AcMarche\Edr\Entity\Presence\Presence;
use AcMarche\Edr\Entity\Scolaire\Ecole;
use AcMarche\Edr\Entity\Traits\AnimateursTrait;
use AcMarche\Edr\Entity\Traits\ArchiveTrait;
use AcMarche\Edr\Entity\Traits\ColorTrait;
use AcMarche\Edr\Entity\Traits\ForfaitTrait;
use AcMarche\Edr\Entity\Traits\IdOldTrait;
use AcMarche\Edr\Entity\Traits\IdTrait;
use AcMarche\Edr\Entity\Traits\PedagogiqueTrait;
use AcMarche\Edr\Entity\Traits\PrixTrait;
use AcMarche\Edr\Entity\Traits\RemarqueTrait;
use AcMarche\Edr\Jour\Repository\JourRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Stringable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Table]
#[ORM\UniqueConstraint(columns: ['date_jour', 'pedagogique', 'plaine_id'])]
#[ORM\Entity(repositoryClass: JourRepository::class)]
#[UniqueEntity(fields: ['date_jour', 'pedagogique', 'plaine'], message: 'Cette valeur existe déjà')]
class Jour implements TimestampableInterface, Stringable
{
    use IdTrait;
    use TimestampableTrait;
    use PrixTrait;
    use ColorTrait;
    use RemarqueTrait;
    use ArchiveTrait;
    use PedagogiqueTrait;
    use ForfaitTrait;
    use AnimateursTrait;
    use PlaineTrait;
    use IdOldTrait;

    /**
     * J'ai mis la definition pour pouvoir mettre le cascade.
     *
     * @var Presence[]
     */
    #[ORM\OneToMany(targetEntity: Presence::class, mappedBy: 'jour', cascade: ['remove'])]
    private Collection|array $presences = [];

    #[ORM\ManyToOne(targetEntity: Plaine::class, inversedBy: 'jours')]
    private ?Plaine $plaine = null;

    /**
     * @var Animateur[]
     */
    #[ORM\ManyToMany(targetEntity: Animateur::class, mappedBy: 'jours')]
    private Collection|array $animateurs = [];

    #[ORM\ManyToMany(targetEntity: Ecole::class)]
    private Collection $ecoles;

    public function __construct(
        #[ORM\Column(name: 'date_jour', type: 'date')]
        private ?DateTimeInterface $date_jour
    ) {
        $this->presences = new ArrayCollection();
        $this->animateurs = new ArrayCollection();
        $this->ecoles = new ArrayCollection();
        $this->prix1 = 0;
        $this->prix2 = 0;
        $this->prix3 = 0;
        $this->forfait = 0;
        $this->pedagogique = false;
    }

    public function __toString(): string
    {
        return $this->date_jour->format('d-m-Y');
    }

    public function getDateJour(): ?DateTimeInterface
    {
        return $this->date_jour;
    }

    public function setDateJour(DateTimeInterface $date_jour): self
    {
        $this->date_jour = $date_jour;

        return $this;
    }

    /**
     * @return Collection|Presence[]
     */
    public function getPresences(): Collection
    {
        return $this->presences;
    }

    public function addPresence(Presence $presence): self
    {
        if (!$this->presences->contains($presence)) {
            $this->presences[] = $presence;
            $presence->setJour($this);
        }

        return $this;
    }

    public function removePresence(Presence $presence): self
    {
        // set the owning side to null (unless already changed)
        if ($this->presences->removeElement($presence) && $presence->getJour() === $this) {
            $presence->setJour(null);
        }

        return $this;
    }

    /**
     * @return Collection|Ecole[]
     */
    public function getEcoles(): Collection
    {
        return $this->ecoles;
    }

    public function addEcole(Ecole $ecole): self
    {
        if (!$this->ecoles->contains($ecole)) {
            $this->ecoles[] = $ecole;
        }

        return $this;
    }

    public function removeEcole(Ecole $ecole): self
    {
        $this->ecoles->removeElement($ecole);

        return $this;
    }
}

src/Enfant/Form/EnfantEditForParentType.php
<?php

namespace AcMarche\Edr\Enfant\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

final class EnfantEditForParentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        $formBuilder
            ->remove('accueilEcole')
            ->remove('archived')
            ->remove('ordre')
            ->remove('groupe_scolaire');
    }

    public function getParent(): ?string
    {
        return EnfantType::class;
    }
}

src/Controller/Admin/EcoleController.php
<?php

namespace AcMarche\Edr\Controller\Admin;

use AcMarche\Edr\Ecole\Form\EcoleType;
use AcMarche\Edr\Ecole\Message\EcoleCreated;
use AcMarche\Edr\Ecole\Message\EcoleDeleted;
use AcMarche\Edr\Ecole\Message\EcoleUpdated;
use AcMarche\Edr\Ecole\Repository\EcoleRepository;
use AcMarche\Edr\Enfant\Repository\EnfantRepository;
use AcMarche\Edr\Entity\Scolaire\Ecole;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/ecole')]
#[IsGranted('ROLE_MERCREDI_ADMIN')]
final class EcoleController extends AbstractController
{
    public function __construct(
        private readonly EcoleRepository $ecoleRepository,
        private readonly EnfantRepository $enfantRepository,
        private readonly MessageBusInterface $dispatcher
    ) {
    }

    #[Route(path: '/', name: 'edr_admin_ecole_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render(
            '@AcMarcheEdrAdmin/ecole/index.html.twig',
            [
                'ecoles' => $this->ecoleRepository->findAllOrderByNom(),
            ]
        );
    }

    #[Route(path: '/new', name: 'edr_admin_ecole_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $ecole = new Ecole();
        $form = $this->createForm(EcoleType::class, $ecole);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->ecoleRepository->persist($ecole);
            $this->ecoleRepository->flush();

            $this->dispatcher->dispatch(new EcoleCreated($ecole->getId()));

            return $this->redirectToRoute('edr_admin_ecole_show', [
                'id' => $ecole->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheEdrAdmin/ecole/new.html.twig',
            [
                'ecole' => $ecole,
                'form' => $form,
            ]
        );
    }

    #[Route(path: '/{id}', name: 'edr_admin_ecole_show', methods: ['GET'])]
    public function show(Ecole $ecole): Response
    {
        $enfants = $this->enfantRepository->findByEcoles([$ecole]);

        return $this->render(
            '@AcMarcheEdrAdmin/ecole/show.html.twig',
            [
                'ecole' => $ecole,
                'enfants' => $enfants,
            ]
        );
    }

    #[Route(path: '/{id}/edit', name: 'edr_admin_ecole_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ecole $ecole): Response
    {
        $form = $this->createForm(EcoleType::class, $ecole);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->ecoleRepository->flush();

            $this->dispatcher->dispatch(new EcoleUpdated($ecole->getId()));

            return $this->redirectToRoute('edr_admin_ecole_show', [
                'id' => $ecole->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheEdrAdmin/ecole/edit.html.twig',
            [
                'ecole' => $ecole,
                'form' => $form,
            ]
        );
    }

    #[Route(path: '/{id}/delete', name: 'edr_admin_ecole_delete', methods: ['POST'])]
    public function delete(Request $request, Ecole $ecole): RedirectResponse
    {
        if ($this->isCsrfTokenValid('delete' . $ecole->getId(), $request->request->get('_token'))) {
            if ([] !== $this->enfantRepository->findByEcoles([$ecole])) {
                $this->addFlash('danger', 'L\'école contient des enfants et ne peut être supprimée');

                return $this->redirectToRoute('edr_admin_ecole_show', [
                    'id' => $ecole->getId(),
                ]);
            }

            $ecoleId = $ecole->getId();
            $this->ecoleRepository->remove($ecole);
            $this->ecoleRepository->flush();
            $this->dispatcher->dispatch(new EcoleDeleted($ecoleId));
        }

        return $this->redirectToRoute('edr_admin_ecole_index');
    }
}

src/Controller/Admin/EnfantController.php
<?php

namespace AcMarche\Edr\Controller\Admin;

use AcMarche\Edr\Enfant\Form\EnfantType;
use AcMarche\Edr\Enfant\Form\SearchEnfantType;
use AcMarche\Edr\Enfant\Handler\EnfantHandler;
use AcMarche\Edr\Enfant\Message\EnfantCreated;
use AcMarche\Edr\Enfant\Message\EnfantDeleted;
use AcMarche\Edr\Enfant\Message\EnfantUpdated;
use AcMarche\Edr\Enfant\Repository\EnfantRepository;
use AcMarche\Edr\Entity\Enfant;
use AcMarche\Edr\Entity\Tuteur;
use AcMarche\Edr\Plaine\Repository\PlainePresenceRepository;
use AcMarche\Edr\Presence\Repository\PresenceRepository;
use AcMarche\Edr\Presence\Utils\PresenceUtils;
use AcMarche\Edr\Relation\Repository\RelationRepository;
use AcMarche\Edr\Search\SearchHelper;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/enfant')]
#[IsGranted('ROLE_MERCREDI_ADMIN')]
final class EnfantController extends AbstractController
{
    public function __construct(
        private readonly EnfantRepository $enfantRepository,
        private readonly EnfantHandler $enfantHandler,
        private readonly RelationRepository $relationRepository,
        private readonly PresenceRepository $presenceRepository,
        private readonly PresenceUtils $presenceUtils,
        private readonly SearchHelper $searchHelper,
        private readonly PlainePresenceRepository $plainePresenceRepository,
        private readonly MessageBusInterface $dispatcher
    ) {
    }

    #[Route(path: '/', name: 'edr_admin_enfant_index', methods: ['GET', 'POST'])]
    #[Route(path: '/all/{all}', name: 'edr_admin_enfant_all', methods: ['GET'])]
    public function index(Request $request): Response
    {
        $form = $this->createForm(SearchEnfantType::class);
        $form->handleRequest($request);

        $enfants = [];
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $this->searchHelper->saveSearch(SearchHelper::ENFANT_LIST, $data);
            $enfants = $this->enfantRepository->search(
                $data['nom'],
                $data['ecole'],
                $data['annee_scolaire'],
                $data['archived']
            );
        }
$response = new Response(null, $form->isSubmitted() ? Response::HTTP_ACCEPTED : Response::HTTP_OK);
        return $this->render(
            '@AcMarcheEdrAdmin/enfant/index.html.twig',
            [
                'enfants' => $enfants,
                'form' => $form->createView(),
                'search' => $form->isSubmitted(),
            ]
        ,$response);
    }

    #[Route(path: '/new/{id}', name: 'edr_admin_enfant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, Tuteur $tuteur): Response
    {
        $enfant = new Enfant();
        $form = $this->createForm(EnfantType::class, $enfant);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->enfantHandler->newHandle($enfant, $tuteur);
            $this->dispatcher->dispatch(new EnfantCreated($enfant->getId()));

            return $this->redirectToRoute('edr_admin_enfant_show', [
                'id' => $enfant->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheEdrAdmin/enfant/new.html.twig',
            [
                'enfant' => $enfant,
                'form' => $form,
            ]
        );
    }

    #[Route(path: '/{id}', name: 'edr_admin_enfant_show', methods: ['GET'])]
    public function show(Enfant $enfant): Response
    {
        $relations = $this->relationRepository->findByEnfant($enfant);
        $data = $this->presenceRepository->findByEnfant($enfant);
        $presencesGrouped = $this->presenceUtils->groupByYear($data);
        $fratries = $this->relationRepository->findFrateries($enfant);
        $plaines = $this->plainePresenceRepository->findPlainesByEnfant($enfant);
        $year = date('Y');

        return $this->render(
            '@AcMarcheEdrAdmin/enfant/show.html.twig',
            [
                'enfant' => $enfant,
                'fratries' => $fratries,
                'relations' => $relations,
                'prensencesGrouped' => $presencesGrouped,
                'plaines' => $plaines,
                'currentYear' => $year,
            ]
        );
    }

    #[Route(path: '/{id}/edit', name: 'edr_admin_enfant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Enfant $enfant): Response
    {
        $form = $this->createForm(EnfantType::class, $enfant);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->enfantRepository->flush();

            $this->dispatcher->dispatch(new EnfantUpdated($enfant->getId()));

            return $this->redirectToRoute('edr_admin_enfant_show', [
                'id' => $enfant->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheEdrAdmin/enfant/edit.html.twig',
            [
                'enfant' => $enfant,
                'form' => $form,
            ]
        );
    }

    #[Route(path: '/{id}/delete', name: 'edr_admin_enfant_delete', methods: ['POST'])]
    public function delete(Request $request, Enfant $enfant): RedirectResponse
    {
        if ($this->isCsrfTokenValid('delete' . $enfant->getId(), $request->request->get('_token'))) {
            $enfantId = $enfant->getId();
            $this->enfantRepository->remove($enfant);
            $this->enfantRepository->flush();
            $this->dispatcher->dispatch(new EnfantDeleted($enfantId));
        }

        return $this->redirectToRoute('edr_admin_enfant_index');
    }
}

src/Controller/Animateur/EnfantController.php
<?php

namespace AcMarche\Edr\Controller\Animateur;

use AcMarche\Edr\Enfant\Form\SearchEnfantForAnimateurType;
use AcMarche\Edr\Enfant\Repository\EnfantRepository;
use AcMarche\Edr\Entity\Enfant;
use AcMarche\Edr\Presence\Repository\PresenceRepository;
use AcMarche\Edr\Relation\Repository\RelationRepository;
use AcMarche\Edr\Sante\Handler\SanteHandler;
use AcMarche\Edr\Sante\Utils\SanteChecker;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/enfant')]
final class EnfantController extends AbstractController
{
    use GetAnimateurTrait;

    public function __construct(
        private readonly EnfantRepository $enfantRepository,
        private readonly SanteHandler $santeHandler,
        private readonly SanteChecker $santeChecker,
        private readonly PresenceRepository $presenceRepository,
        private readonly RelationRepository $relationRepository
    ) {
    }

    #[Route(path: '/', name: 'edr_animateur_enfant_index', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MERCREDI_ANIMATEUR')]
    public function index(Request $request): Response
    {
        if (($hasAnimateur = $this->hasAnimateur()) instanceof Response) {
            return $hasAnimateur;
        }

        $nom = null;
        $form = $this->createForm(
            SearchEnfantForAnimateurType::class,
            null,
            [
                'animateur' => $this->animateur,
            ]
        );
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $nom = $data['nom'];
        }

        $enfants = $this->enfantRepository->searchForAnimateur($this->animateur, $nom);

        return $this->render(
            '@AcMarcheEdrAnimateur/enfant/index.html.twig',
            [
                'enfants' => $enfants,
                'form' => $form,
            ]
        );
    }

    #[Route(path: '/{uuid}', name: 'edr_animateur_enfant_show', methods: ['GET'])]
    #[IsGranted('enfant_show', subject: 'enfant')]
    public function show(Enfant $enfant): Response
    {
        $santeFiche = $this->santeHandler->init($enfant);
        $ficheSanteComplete = $this->santeChecker->isComplete($santeFiche);
        $presences = $this->presenceRepository->findByEnfant($enfant);
        $relations = $this->relationRepository->findByEnfant($enfant);

        return $this->render(
            '@AcMarcheEdrAnimateur/enfant/show.html.twig',
            [
                'enfant' => $enfant,
                'presences' => $presences,
                'relations' => $relations,
                'ficheSanteComplete' => $ficheSanteComplete,
            ]
        );
    }
}

templates/ecole/enfant/_accueils.html.twig
<div class="card">

    <h5 class="card-header">Ses accueils </h5>
    <div class="card-body">
        {% if accueils | length > 0 %}
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Date</th>
                    <th title="Nombre de demi heure">Nb d'unité</th>
                    <th>Matin/soir</th>
                    <th>Retard ?</th>
                </tr>
                </thead>
                <tbody>
                {% for accueil in accueils %}
                    <tr>
                        <td>
                            <a href="{{ path('edr_ecole_accueil_show', { 'uuid': accueil.uuid }) }}">
                                {{ accueil.dateJour|format_date('full') }}
                            </a>
                        </td>
                        <td>
                            {{ accueil.duree }}
                        </td>
                        <td>
                            {{ accueil.heure }}
                        </td>
                        <td>
                            {{ accueil.heureRetard ? accueil.heureRetard|format_datetime('none', 'short') }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            Aucun
        {% endif %}
    </div>
</div>

templates/ecole/enfant/_actions.html.twig
<div class="d-grid gap-2 d-md-block mb-3">

    {% include '@AcMarcheEdr/ecole/enfant/_btn_add_accueil.html.twig' %}

    <a href="{{ path('edr_ecole_sante_fiche_show', { 'uuid': enfant.uuid }) }}" role="button"
       class="btn btn-primary"><i class="ti ti-heartbeat"></i> Fiche santé</a>

    <a href="{{ path('edr_ecole_accueil_retard', { 'uuid': enfant.uuid }) }}" role="button"
       class="btn btn-primary"><i class="ti ti-hourglass-half"></i> Retard</a>

    <a href="{{ path('edr_ecole_enfant_index') }}" class="btn btn-primary" role='button'><i
                class="ti ti-list"></i>
        Retour à la Liste</a>
</div>

templates/ecole/enfant/_btn_add_accueil.html.twig
{% if relations | length == 0 %}

        <button disabled="disabled" type="button" role="button" title="Aucun tuteur"
                class="btn btn-primary"><i
                    class="ti ti-plus"></i> Ajouter un accueil, Aucun tuteur !
        </button>

{% elseif relations | length == 1 %}
    {% set tuteur = relations|first.tuteur %}

        <a href="{{ path('edr_ecole_accueil_new', { 'enfant': enfant.id, 'tuteur': tuteur.id }) }}" role="button"
           class="btn btn-primary"><i
                    class="ti ti-plus"></i> Ajouter un accueil</a>

{% else %}

    <div class="dropdown mb-2 mr-2">
        <a class="btn btn-primary dropdown-toggle"
           href="#"
           role="button" id="dropdownMenuLink"
           data-bs-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            <i class="ti ti-plus"></i> Ajouter un accueil
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            {% for relation in relations %}
                {% set tuteur = relation.tuteur %}
                <a class="dropdown-item"
                   href="{{ path('edr_ecole_accueil_new', { 'enfant': enfant.id, 'tuteur': tuteur.id }) }}">
                    Sous la garde de <i>{{ tuteur }}</i></a>
            {% endfor %}
        </div>
    </div>
{% endif %}

templates/ecole/enfant/_form.html.twig
{{ form_start(form) }}
{{ form_errors(form) }}
<div class="row">
    <div class="col-6 col-md-4">
        {{ form_row(form.nom) }}
    </div>
    <div class="col-6 col-md-4">
        {{ form_row(form.prenom) }}
    </div>
    <div class="col-6 col-md-4">
        {{ form_row(form.birthday) }}
    </div>
    <div class="col-6 col-md-4">
        {{ form_row(form.sexe) }}
    </div>
    <div class="col-6 col-md-4">
        {{ form_row(form.ecole) }}
    </div>
    <div class="col-6 col-md-4">
        {{ form_row(form.annee_scolaire) }}
    </div>
    <div class="col-12 col-md-12">
        {{ form_row(form.photoAutorisation) }}
    </div>
    <div class="col-12 col-md-12">
        {{ form_row(form.remarque) }}
    </div>
    <div class="col-12 col-md-12">
        {{ form_row(form.photo) }}
    </div>
</div>
<br/>

<button class="btn btn-primary mr-1 mb-2" type="submit"><i class="ti ti ti-device-floppy" aria-hidden="true"></i>
    Sauvegarder
</button>

{{ form_end(form) }}

templates/ecole/enfant/_list.html.twig
<table class="table table-bordered">
    <tr>
        <th>Nom</th>
        <th>Ecole</th>
        <th>Inscrit accueil ?</th>
        <th>Modifier</th>
    </tr>
    {% for enfant in enfants %}
        <tr>
            <td>
                <a href="{{ path('edr_ecole_enfant_show', {'uuid': enfant.uuid}) }}">
                    {{ enfant }}
                </a>
            </td>
            <td>{{ enfant.ecole }}</td>
            <td>{{ enfant.isAccueilEcole ? 'Oui' : 'Non' }}</td>
            <td><a class="btn btn-warning btn-sm" role="button"
                   href="{{ path('edr_ecole_enfant_edit', {'uuid': enfant.uuid}) }}">Modifier</a></td>
        </tr>
    {% else %}
        <tr>
            <td colspan="4">Aucun enfant trouvé</td>
        </tr>
    {% endfor %}
</table>

templates/ecole/enfant/_plaines.html.twig
<div class="card">

    <h5 class="card-header">Ses plaines</h5>
    <div class="card-body">


            <ul class="list-group">
                {% for plaine in plaines %}
                    <li class="list-group-item">
                        <a href="{{ path('edr_parent_plaine_show', {'id': plaine.id}) }}">{{ plaine }}</a>
                    </li>
                {% endfor %}

            </ul>
    </div>
</div>

templates/ecole/enfant/_presences.html.twig
<div class="card">

    <h5 class="card-header">Ses présences </h5>
    <div class="card-body">
        {% include '@AcMarcheEdrParent/presence/_list.html.twig' %}
    </div>
</div>

templates/ecole/enfant/_search.html.twig
{{ form_start(form, { 'attr': {'class': 'row row-cols-lg-auto g-3 align-items-center hidden-print'}}) }}
{{ form_errors(form) }}

{{ form_row(form.nom, {label_attr: {class: 'sr-only'}, attr:{'class': ' my-1 mr-sm-2'} }) }}
{{ form_row(form.accueil, {label_attr: {class: 'mr-2 sr-on2ly'}, attr:{'class': ' my-1 mr-2 mr-sm-2'} }) }}

<div class="col-12">
    <button class="btn btn-primary mr-1" type="submit"><i class="ti ti-search"></i> Rechercher</button>
</div>

{{ form_rest(form) }}
{{ form_end(form) }}
<br />

templates/ecole/enfant/edit.html.twig
{% extends '@AcMarcheEdrEcole/layout.html.twig' %}

{% block body %}

    <div class="card mb-3">
        <div class="card-header">
            <h3>{{ enfant }}</h3>
        </div>

        <div class="card-body">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            {{ form_row(form.accueil_ecole) }}
            <br/>

            <button class="btn btn-primary mr-1 mb-2" type="submit"><i class="ti ti ti-device-floppy" aria-hidden="true"></i>
                Sauvegarder
            </button>

            {{ form_end(form) }}
        </div>

        <div class="card-footer">
            <a href="{{ path('edr_ecole_enfant_index') }}" class="mt-4">
                <i class="ti ti-long-arrow-alt-left"></i> Annuler
            </a>
        </div>
    </div>

{% endblock %}

templates/ecole/enfant/index.html.twig
{% extends '@AcMarcheEdrEcole/layout.html.twig' %}

{% block body %}
    <div class="card mb-3">

        <div class="card-header">
            <h3 class="w-50 d-inline">Liste des enfants</h3>
        </div>

        <div class="card-body">

            <div class="alert alert-success">
                La liste ci-dessous affiche les enfants qui <strong>viennent au matin et/ou au soir.</strong><br/>
                Pour afficher les enfants, qui ne sont <strong>pas encore inscrits</strong> décochez la case et cliquez
                sur rechercher.
            </div>

            {% include '@AcMarcheEdrEcole/enfant/_search.html.twig' %}
            {% include '@AcMarcheEdrEcole/enfant/_list.html.twig' %}
        </div>

    </div>
{% endblock %}

templates/ecole/enfant/sante_fiche.html.twig
{% extends '@AcMarcheEdrEcole/layout.html.twig' %}

{% block body %}

    <div class="card mb-3">
        <div class="card-header">
            <h3>Fiche santé de {{ enfant }}</h3>
        </div>
        <div class="card-body">

            <a href="{{ path('edr_commun_export_sante_fiche_pdf', { 'uuid': enfant.uuid }) }}" role="button"
               class="btn btn-primary"><i class="ti ti-file-pdf"></i> Pdf</a>
            <br/> <br/>


            {% include '@AcMarcheEdr/sante/_detail.html.twig' %}
        </div>
    </div>

{% endblock %}

templates/ecole/enfant/show.html.twig
{% extends '@AcMarcheEdrEcole/layout.html.twig' %}

{% block body %}

    <div class="card mb-2">
        <h3 class="card-header">{{ enfant }}</h3>
        <div class="card-body">
            {% include '@AcMarcheEdrEcole/enfant/_actions.html.twig' %}
            <div class="d-flex">
                <div class="flex-shrink-0">
                    {% include '@AcMarcheEdr/commun/enfant/_photo.html.twig' %}
                </div>
                <div class="flex-grow-1 ms-3">
                    {% include '@AcMarcheEdr/commun/enfant/_identite.html.twig' %}
                    <br/>
                    Inscris aux accueil du matin et soir:
                    {% if enfant.isAccueilEcole %}
                        Oui
                    {% else %}
                        Non
                    {% endif %}
                    <br/>
                </div>
            </div>
            <br/>
        </div>
    </div>

    {% include '@AcMarcheEdr/ecole/enfant/_accueils.html.twig' %}

{% endblock %}